# Generated by Django 2.1.5 on 2019-01-25 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fast_drf.mixins.expose_api_model_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('code', models.CharField(max_length=16, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(fast_drf.mixins.expose_api_model_mixin.ExposeApiModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SurveyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(fast_drf.mixins.expose_api_model_mixin.ExposeApiModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='survey',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='survey.SurveyGroup'),
        ),
    ]
